### ISSUE TITLE
Don't work! 

### ISSUE THREAD

**Issue by nahojj** [TimPerry/acf-post-type-selector#11]
Nothing works and the readme file is a old one  ... DONT USE!

**Comment by gnowland** [comment]
It's working for me, what specifically are you having problems with?

**Comment by TimPerry** [comment]
@gnowland I've merged your PR. @nahojj Does this fix your problem? In terms of the readme I've not felt the need to update it in a while as it's somewhat self explanatory? Probably worth rewriting this whole plugin if enough people are finding it useful.
