### ISSUE TITLE
Improve post type labeling

### ISSUE THREAD

**Issue by mcaskill** [TimPerry/acf-post-type-selector#13]
For example, if two post types share the same label name it becomes difficult to differentiate the two without looking at the values of each post type.

I suggest using `acf_get_pretty_post_types()`, which is what ACF uses for its relational field types (Post Object, Page Link, Relationship). The function handles label conflicts by appending the post type key to the label.

**Comment by TimPerry** [comment]
Howdy,

I no longer use wordpress in my day-to-day so not actively maintaining this project. PRs are welcome. If I get time over the holidays this year I might take a bit of time to update it and add some features.

Cheers,

Tim

**Comment by tyrann0us** [comment]
Hi @mcaskill, since @TimPerry doesn't maintain this project any longer, he added me as contributor. Are you willing to submit a PR for this issue? Thanks!

**Comment by tyrann0us** [comment]
@mcaskill, thank you for the PR. I appreciate your work to support ACF v4 (and even v3!).

Here's my two cents: Most of the code is made up of helper functions for v3 and v4 which increases the overall amount of code to be maintained. In fact, only 8 of the 325 additions target v5 (8/25 deletions).
Additionally, an update to v5 for the free version has been announced (see #22).

Wouldn't it be better to only include a fix for v5? I mean, the plugin works, this PR is "just" an enhancement. IMHO it would be OK to exclude v4 users given the facts above.

What do you think?

**Comment by mcaskill** [comment]
> Wouldn't it be better to only include a fix for v5? I mean, the plugin works, this PR is "just" an enhancement. IMHO it would be OK to exclude v4 users given the facts above.
— @tyrann0us 

I agree with you to make #21 v5 exclusive. I hesitated about pushing the helpers to v3 and v4 because it's a rare use case to begin with.
