### ISSUE TITLE
Add for attribut to labels and id attribut to inputs

### ISSUE THREAD

**Issue by tyrann0us** [TimPerry/acf-post-type-selector#15]
Hi,
when using radio boxes (not tested with checkboxes) clicking a label doesn't select the corresponding input.
Simply add a combination of `for` and `id` attributes to the `label` and `input` elements to make it working,
Thanks!

**Comment by TimPerry** [comment]
Howdy,

I no longer use wordpress in my day-to-day so not actively maintaining this project. PRs are welcome. If I get time over the holidays this year I might take a bit of time to update it and add some features.

Cheers,

Tim
