### ISSUE TITLE
Transfer ownership?

### ISSUE THREAD

**Issue by tyrann0us** [TimPerry/acf-post-type-selector#19]
Hi @TimPerry,
since you're "out of WordPress", have you thought about transferring ownership of this repository?

I'd be willing to overtake it.

**Comment by TimPerry** [comment]
Hey, sure. Makes a lot of sense.

**Comment by tyrann0us** [comment]
Hi @TimPerry,
do you mind adding @mcaskill as a collaborator? He's way more active working on this project than me.

**Comment by TimPerry** [comment]
Hey, sorry. Clearly got busy again! I will add @mcaskill on now.

**Comment by TimPerry** [comment]
I've sorted some of my notifications out now as well, so I should be a bit more responsive. Thanks for all the work guys.
