### ISSUE TITLE
Incompatible with v5

### ISSUE THREAD

**Issue by ninetienne** [TimPerry/acf-post-type-selector#5]
The field doesn't appear in ACF5.

**Comment by darknailblue** [comment]
+1 any plans on making this compatible with v5?

**Comment by elawn** [comment]
> +1 any plans on making this compatible with v5?

+1

**Comment by danimalweb** [comment]
+1

**Comment by pimschaaf** [comment]
Checkout @thomasdebruin's pull request: https://github.com/TimPerry/acf-post-type-selector/pull/7. Does the trick.

**Comment by TimPerry** [comment]
Sorry guys, don't know how I missed that PR. Merged it now.

**Comment by TimPerry** [comment]
Will close this as I believe the PR is good. Please reopen is that is not the case.
