### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by david-treblig** [TimPerry/acf-post-type-selector#9]
For some reason, your plugin (and not other acf plugins) started giving me a wrong URL for input.css and input.js.

[Look at line 43 to 45](https://github.com/TimPerry/acf-post-type-selector/blob/master/post-type-selector-v5.php)

It seems that the full path of the server gets pushed in the 'dir' parameter which messes up the enqueue styles and enqueue scripts later on in the code.

I just want to add that the plugin was working fine one day and the other day not, so it might have to do with a param on my server or something like that, but I just wanted to put it here in case someone gets the same problem.

**Comment by TimPerry** [comment]
PR #10 should resolve this. If not reopen.
